# Generated by Django 3.1.4 on 2020-12-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('logo', models.URLField()),
                ('numReviews', models.IntegerField()),
                ('totRating', models.FloatField()),
                ('avgRating', models.FloatField()),
                ('avgLearningMentorshipRating', models.FloatField()),
                ('totLearningMentorshipRating', models.FloatField()),
                ('avgMeaningfulWorkRating', models.FloatField()),
                ('totMeaningfulWorkRating', models.FloatField()),
                ('avgWorkLifeBalanceRating', models.FloatField()),
                ('totWorkLifeBalanceRating', models.FloatField()),
                ('totHourlySalary', models.FloatField()),
                ('avgHourlySalary', models.FloatField()),
                ('minHourlySalary', models.FloatField()),
                ('maxHourlySalary', models.FloatField()),
                ('hourlySalaryCurrency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('totRating', models.FloatField()),
                ('avgRating', models.FloatField()),
                ('avgLearningMentorshipRating', models.FloatField()),
                ('totLearningMentorshipRating', models.FloatField()),
                ('avgMeaningfulWorkRating', models.FloatField()),
                ('totMeaningfulWorkRating', models.FloatField()),
                ('avgWorkLifeBalanceRating', models.FloatField()),
                ('totWorkLifeBalanceRating', models.FloatField()),
                ('totHourlySalary', models.FloatField()),
                ('avgHourlySalary', models.FloatField()),
                ('minHourlySalary', models.FloatField()),
                ('maxHourlySalary', models.FloatField()),
                ('hourlySalaryCurrency', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('author', models.EmailField(max_length=254)),
                ('overallRating', models.FloatField()),
                ('learningMentorshipRating', models.FloatField()),
                ('meaningfulWorkRating', models.FloatField()),
                ('workLifeBalanceRating', models.FloatField()),
                ('salary', models.FloatField()),
                ('salaryCurrency', models.CharField(max_length=5)),
                ('salaryPeriod', models.CharField(choices=[('YEARLY', 'Yearly'), ('WEEKLY', 'Weekly'), ('HOURLY', 'Hourly')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
        ),
    ]
