# Generated by Django 3.1.4 on 2020-12-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='salaryCurrency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='salary',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='HourlySalary',
        ),
    ]
