# Generated by Django 3.1.4 on 2020-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hourlySalaryCurrency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='hourlySalaryCurrency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='salaryCurrency',
            field=models.CharField(max_length=3),
        ),
    ]
