# Generated by Django 3.1.4 on 2020-12-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201231_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='aaaa', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='subdivision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
