# Generated by Django 3.1.4 on 2021-01-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210101_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='learningMentorship',
            new_name='rating_learning_mentorship',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='meaningfulWork',
            new_name='rating_meaningful_work',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='overall',
            new_name='rating_overall',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='workLifeBalance',
            new_name='rating_work_life_balance',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='salaryCurrency',
            new_name='salary_currency',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
