# Generated by Django 3.1.4 on 2021-01-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210101_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='salary_usd',
            field=models.PositiveIntegerField(blank=True, default=19),
            preserve_default=False,
        ),
    ]
