# NOTE: THIS SCHEMA IS NOT ALWAYS CORRECT.
#       It is placed here mainly as a quick reference. It may be out of date and should not be used as a source of truth.
#       The correct source of truth is the GraphQL schema on the server. It can be fetched and converted into types by running `npm run api:generate-types`.

enum PayPeriod {
  HOURLY
  MONTHLY
}

enum Currency {
  USD
  CAD
  EUR
  OTHER
}

type Company {
  name: String!
  desc: String
  slug: String!
  reviews: [Review!]!
  numReviews: Int!
  totalReviewScore: Int!
  avgReviewScore: Float!
}

type Job {
  title: String!
  company: Company!
  minSalary: Int!
  maxSalary: Int!
  avgSalary: Int!
  reviews: [Review!]!
  numReviews: Int!
  totalReviewScore: Int!
  avgReviewScore: Float!
}

type Review {
  company: Company!
  job: Job!
  location: String
  body: String!
  salary: Int!
  salaryPeriod: PayPeriod!
  salaryCurrency: Currency!
  overallScore: Int!
  learningMentorshipScore: Int
  workLifeBalanceScore: Int
  meaningfulWorkScore: Int
}
