name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm run lint
      - name: Build & check types
        run: npm run build
