name: Frontend CI
on: push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run type-checker
        run: npm run type-check

  unit-tests:
    if: contains(github.ref, 'release') || contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit:ci
        env:
          REACT_APP_DB_GRAPHQL_API_URL: ${{ secrets.REACT_APP_DB_GRAPHQL_API_URL }}

  e2e-tests:
    if: contains(github.ref, 'release') || contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run E2E/visual regression tests
        run: npm run test:e2e:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          REACT_APP_DB_GRAPHQL_API_URL: ${{ secrets.REACT_APP_DB_GRAPHQL_API_URL }}
