# name: master

# on:
#   pull_request:
#     branches:
#       - master

# jobs:
#   visual_tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@master
#         with:
#           fetch-depth: 1
#       - name: Install dependencies
#         run: npm ci
#       - name: Run visual tests with Percy
#         run: npx percy exec -- node ./server/scripts/runVisualTests.js
#         env:
#           PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
#           REACT_APP_DB_GRAPHQL_API_URL: ${{ secrets.REACT_APP_DB_GRAPHQL_API_URL }}
#   functionality_tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@master
#         with:
#           fetch-depth: 1
#       - name: Install dependencies
#         run: npm ci
#       - name: Run Jest tests
#         run: npm run test:nowatch
