name: visual tests

on:
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Percy
        run: npx percy snapshot ./public
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}